# Generated by Django 4.2.7 on 2023-11-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='CompanyMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('cin_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=20)),
                ('tan_no', models.CharField(max_length=20)),
                ('gst_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_company_mst',
            },
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iso_code', models.CharField(max_length=5)),
                ('country_code', models.CharField(max_length=5)),
                ('currency_code', models.CharField(max_length=5)),
                ('currency_symbol', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_country_currency',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(max_length=255)),
                ('master_value', models.CharField(max_length=255)),
                ('master_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_master',
            },
        ),
        migrations.CreateModel(
            name='ProductMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('category_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
            ],
            options={
                'db_table': 'tbl_product_mst',
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_uom',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tbl_user_detail',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wishlist', models.BooleanField(default=True)),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.productmst')),
                ('user_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userdetail')),
            ],
            options={
                'db_table': 'tbl_wishlist',
            },
        ),
        migrations.CreateModel(
            name='TokenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access_token', models.CharField(max_length=255)),
                ('user_refresh_token', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('user_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userdetail')),
            ],
            options={
                'db_table': 'tbl_token_master',
            },
        ),
        migrations.CreateModel(
            name='RoleMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('company_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.companymst')),
            ],
            options={
                'db_table': 'tb_role_mst',
            },
        ),
        migrations.AddField(
            model_name='productmst',
            name='uom_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.uom'),
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.productmst')),
            ],
            options={
                'db_table': 'tbl_details_mst',
            },
        ),
        migrations.CreateModel(
            name='OrderMst',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='portal.master')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='portal.master')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userdetail')),
            ],
            options={
                'db_table': 'tbl_order_mst',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ordermst')),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.productmst')),
            ],
            options={
                'db_table': 'tbl_order_detail',
            },
        ),
        migrations.AddField(
            model_name='companymst',
            name='ownership_status_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.master'),
        ),
        migrations.CreateModel(
            name='CartMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userdetail')),
            ],
            options={
                'db_table': 'tbl_cart_mst',
            },
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cartmst')),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.productmst')),
            ],
            options={
                'db_table': 'tbl_cart_detail',
            },
        ),
    ]
