# Generated by Django 4.2.7 on 2023-11-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_productbrand_userdetail_user_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='role_ref_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.rolemst'),
            preserve_default=False,
        ),
    ]
