# Generated by Django 4.2.7 on 2023-11-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_userdetail_role_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_url', models.CharField(max_length=255)),
                ('app_icon', models.CharField(max_length=255)),
                ('menu_name', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.rolemst')),
            ],
        ),
        migrations.AlterField(
            model_name='cartmst',
            name='user_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='ordermst',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='tokenmaster',
            name='user_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_url', models.CharField(max_length=255)),
                ('menu_name', models.CharField(max_length=255)),
                ('main_menu_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='StockMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.productmst')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('stock_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.stockmst')),
            ],
        ),
    ]
